/* FICHERO PARA LA CREACIÓN DE SECUENCIAS */

CREATE SEQUENCE seqVideojuego
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCACHE;

CREATE SEQUENCE seqOrganizador
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCACHE;